---
title: "git_01"
author: "Daniel Purri"
date: "Spring semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

 
  A BOAT beneath a sunny sky,    
Lingering onward dreamily.    
In an evening of July --  
Children three that nestle near,  
Eager eye and willing ear.   
  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

  Two roads diverged in a yellow wood,  
And sorry I could not travel both.  
And be one traveler, long I stood.  
And looked down one as far as I could.  
To where it bent in the undergrowth;  
  


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make. 
      The billows smooth and bright —  
And this was odd, because it was. 
      The middle of the night.  
  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there. 
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
        

## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->

This is, perhaps, the year to learn to be big.  
Spruce tree big. Cliffside big. Big as mesa,  
as mountain lake. Big as in cosmos, as in love.  
Being small has never served me— constricting,  
contorting, trying to fit into a room, into shoes,  
into a name. Let this be the year to escape all those little  
rules with those little shoulds, all those little. 
cages with their little locks. Time to make of myself. 
a key, time to lean into immensity. Time to supersize. 
communion, time to grow beyond self. Time to. 
open, to unwall, to do as the universe does,  
accelerating as it expands, not rushing toward. 
something else, but changing the scale of space itself.  
  